## Create User
POST http://localhost:3000/authentication/signup
Content-Type: application/json

{
    "firstname": "matthew",
    "lastname": "bisnar",
    "password": "root",
    "email": "matthewobisnar22@gmail.com"
}

### Sign In User
POST http://localhost:3000/authentication/signin
Content-Type: application/json

{
    "email":"matthewobisnar@gmail.com",
    "password": "root"
}