version: '3'
services:
  nestjs:
    image: nestjs_image_dev
    container_name: nestjs_container_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./env/.env.development
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: npm run start:dev

  migration: 
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./env/.env.development
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: npx typeorm migration:run -d  dist/shared/db/connections/type.orm.database.migration.source.js 
    depends_on:
      - nestjs