version: '3'
services:
 app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run migration:up:dev && npm run start:dev