version: '3'
services:
  nestjs:
    image: ghcr.io/matthewobisnar/nestjs_image_prod:latest
    container_name: nestjs_container_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  migration:
    image: ghcr.io/matthewobisnar/nestjs_image_prod:latest
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    command: npx typeorm migration:run -d dist/shared/db/connections/type.orm.database.migration.source.js
    depends_on:
      - nestjs
