version: '3'
services:
  nestjs:
    image: nestjs_image_prod
    container_name: nestjs_conainer_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./env/.env.production
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    networks:
      - nestjs_network_prod
    command: npm run start:prod

networks:
  nestjs_network_prod:
    driver: bridge