version: '3'
services:
  nestjs:
    image: nestjs_image_prod
    container_name: nestjs_container_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - ./env/.env.production
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    networks:
      - nestjs_network_prod
    command: npm run start:prod
    depends_on:
      - postgres

  postgres:
    container_name: postgres_nestjs
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - nestjs_network_prod

networks:
  nestjs_network_prod:
    driver: bridge