version: '3'
services:
    nestjs:
      image: nestjs_image_prod
      container_name: nestjs_container_prod
      build:
        context: .
        dockerfile: Dockerfile
        target: production
      env_file:
        - ./env/.env.production
      ports:
        - "3000:3000"
      environment:
        - CHOKIDAR_USEPOLLING=true
        - NODE_ENV=production
        
    migration: 
      build:
        context: .
        dockerfile: Dockerfile
        target: production
      env_file:
        - ./env/.env.production
      ports:
        - "3001:3000"
      environment:
        - CHOKIDAR_USEPOLLING=true
        - NODE_ENV=production
      command: npx typeorm migration:run -d  dist/shared/db/connections/type.orm.database.migration.source.js 
      depends_on:
        - nestjs