apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres_exporter:9187
    database: postgres
    user: postgres
    password: password
    jsonData:
      sslmode: disable

  - name: InfluxDb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    jsonData:
      sslmode: disable
